"""ps init

Revision ID: 155e449a75c6
Revises: 
Create Date: 2019-07-16 00:11:05.899059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155e449a75c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ps_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id_owner', sa.Integer(), nullable=True),
    sa.Column('user_id_author', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id_author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id_owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ps_files_file_name'), 'ps_files', ['file_name'], unique=False)
    op.create_index(op.f('ix_ps_files_timestamp'), 'ps_files', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ps_files_timestamp'), table_name='ps_files')
    op.drop_index(op.f('ix_ps_files_file_name'), table_name='ps_files')
    op.drop_table('ps_files')
    # ### end Alembic commands ###
