"""user-mat

Revision ID: f0a4a4fd4497
Revises: 54083c7c5332
Create Date: 2019-07-11 11:40:34.095629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a4a4fd4497'
down_revision = '54083c7c5332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserMat',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mat_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['mat_name'], ['mat.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserMat')
    # ### end Alembic commands ###
